### ISSUE TITLE
CDN and HTML integration

### ISSUE THREAD

**Issue by johncarter-** [metaforo/comment3#17]
Hello there! 

I'm looking to use the tipping widget outside of a React context. 

I can see there once was a version: https://webcache.googleusercontent.com/search?q=cache:h6pajerVTXoJ:https://socket.dev/npm/package/%40dforo3/metaforo-sdk&cd=1&hl=en&ct=clnk&gl=uk#user-content-sample-code

The version shown in that cached page is v0.3.5 but that tag is no longer in this repo.

Can you let me know if there's a way to use this widget using a CDN / HTML tag as described in that cached Google page?

**Comment by wliu6v** [comment]
Try this:

```
<script src="
https://cdn.jsdelivr.net/npm/@dforo3/metaforo-sdk@0.4.12/dist/metaforo-sdk.min.js
"></script>
<link href="
https://cdn.jsdelivr.net/npm/@dforo3/metaforo-sdk@0.4.12/dist/metaforo-sdk.min.css
" rel="stylesheet">
```

HTML：
```
<div class='metaforo-tipping' 
 siteName='CommentWidgetDemo' 
 pageId='DemoThread1' 
 receiverAddress='%INPUT_YOUR_ADDRESS%' 
 receiverUsername='%INPUT_YOUR_USERNAME%' 
 receiverChainId='1' 
 theme='light'>
Tipping
</div>
```

Please note that this project was developed to address a specific need in my work and is not a sufficiently generic open-source library. If you have any requirements or encounter any issues, you can leave me a message, but I cannot guarantee prompt fixing

**Comment by johncarter-** [comment]
I very much appreciate your response, given this is not a generic open-source lib 🙏

I am on a development environment with no live receiver data to use here, so have left these attributes with the placeholders.
```
 receiverAddress='%INPUT_YOUR_ADDRESS%' 
 receiverUsername='%INPUT_YOUR_USERNAME%' 
```

Do I need to have some real receiver details here to make the button render properly?

**Comment by wliu6v** [comment]
These two attributes are used when the button is clicked. During the initialization stage, the SDK will traverse the elements on the page with `class=metaforo-tipping` and add a click event to them. When clicked, it will read the corresponding attribute on the element as the target address for tipping. 

Therefore, you should ensure that these two attributes are correct before the click action takes place, otherwise the target of tipping will be an illegal address.

**Comment by johncarter-** [comment]
Thanks, I've updated those two fields with proper info, but the button is still not rendered within that div. No console errors either.

**Comment by johncarter-** [comment]
I can see this working on a codepen: https://codepen.io/johncarter-the-decoder/pen/wvxQKxO

I'll report back if I can find what the issue is my end. Thanks for the help tough.
